### ISSUE TITLE
build deamon on windows

### ISSUE THREAD

**Issue by paul-Code** [CoinProjects/AmsterdamCoin#1]
any help?

`c:\mingw32\bin\ar.exe: creating libmemenv.a
make[1]: Leaving directory `/c/dev/amsterdamcoin_v3.0/src/leveldb'
g++ -c -mthreads -O2 -w -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -fpermissive -g -DWIN32 -D_WINDOWS -DBOOST_THREAD_USE_LIB -DBOOST_SPIRIT_THREADSAFE -DMINIUPNP_STATICLIB -DUSE_UPNP=1 -DUSE_IPV6=1 -DENABLE_WALLET -I/c/dev/amsterdamcoin_v3.0/src/leveldb/include -I/c/dev/amsterdamcoin_v3.0/src/leveldb/helpers -L"/c/dev/amsterdamcoin_v3.0/src" -I"C:\dev\amsterdamcoin_v2.9.9.9-beta-AutoTest\amsterdamcoin_v2.9.9.9-beta-AutoTest\src" -I"C:\dev\deps/db-4.8.30.NC/build_unix" -I"C:\boost-1.50.0-mgw" -I"C:\dev\deps/gmp-6.0.0" -I"C:\dev\deps/openssl-1.0.1p\include" -I"C:\dev\deps/secp256k1/include" -I"C:\dev\deps/miniupnpc" -o obj/txdb-leveldb.o txdb-leveldb.cpp
g++ -mthreads -O2 -w -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -fpermissive -g -DWIN32 -D_WINDOWS -DBOOST_THREAD_USE_LIB -DBOOST_SPIRIT_THREADSAFE -DMINIUPNP_STATICLIB -DUSE_UPNP=1 -DUSE_IPV6=1 -DENABLE_WALLET -I/c/dev/amsterdamcoin_v3.0/src/leveldb/include -I/c/dev/amsterdamcoin_v3.0/src/leveldb/helpers -L"/c/dev/amsterdamcoin_v3.0/src" -I"C:\dev\amsterdamcoin_v2.9.9.9-beta-AutoTest\amsterdamcoin_v2.9.9.9-beta-AutoTest\src" -I"C:\dev\deps/db-4.8.30.NC/build_unix" -I"C:\boost-1.50.0-mgw" -I"C:\dev\deps/gmp-6.0.0" -I"C:\dev\deps/openssl-1.0.1p\include" -I"C:\dev\deps/secp256k1/include" -I"C:\dev\deps/miniupnpc" -Wl,--dynamicbase -Wl,--nxcompat -Wl,--large-address-aware -static -o amsterdamcoind.exe -L"/c/dev/amsterdamcoin_v3.0/src/leveldb" -L"C:\boost-1.50.0-mgw/stage/lib" -L"C:\dev\deps/db-4.8.30.NC/build_unix" -L"C:\dev\deps/openssl-1.0.1p" -L"C:\dev\deps/secp256k1/.libs" -L"C:\dev\deps/miniupnpc" obj/alert.o obj/allocators.o obj/support/cleanse.o obj/base58.o obj/version.o obj/checkpoints.o obj/netbase.o obj/addrman.o obj/crypter.o obj/key.o obj/pubkey.o obj/ecwrapper.o obj/init.o obj/bitcoind.o obj/keystore.o obj/core.o obj/main.o obj/net.o obj/protocol.o obj/rpcclient.o obj/rpcprotocol.o obj/rpcserver.o obj/rpcmisc.o obj/rpcnet.o obj/rpcblockchain.o obj/rpcrawtransaction.o obj/rpcsmessage.o obj/script.o obj/scrypt.o obj/sync.o obj/txmempool.o obj/util.o obj/hash.o obj/noui.o obj/kernel.o obj/pbkdf2.o obj/chainparams.o obj/stealth.o obj/activemasternode.o obj/darksend.o obj/darksend-relay.o obj/instantx.o obj/masternodeconfig.o obj/masternodeman.o obj/masternode.o obj/masternode-payments.o obj/rpcdarksend.o obj/spork.o obj/crypto/hmac_sha256.o obj/crypto/hmac_sha512.o obj/crypto/ripemd160.o obj/crypto/sha1.o obj/crypto/sha256.o obj/crypto/sha512.o obj/smessage.o obj/db.o obj/miner.o obj/rpcdump.o obj/rpcmining.o obj/rpcwallet.o obj/wallet.o obj/walletdb.o obj/txdb-leveldb.o -l leveldb -l memenv -l boost_system-mgw49-mt-s-1_57 -l boost_filesystem-mgw49-mt-s-1_57 -l boost_program_options-mgw49-mt-s-1_57 -l boost_thread-mgw49-mt-s-1_57 -l boost_chrono-mgw49-mt-s-1_57 -l db_cxx -l ssl -l secp256k1 -l crypto -l miniupnpc -l iphlpapi -l mingwthrd -l kernel32 -l user32 -l gdi32 -l comdlg32 -l winspool -l winmm -l shell32 -l comctl32 -l ole32 -l oleaut32 -l uuid -l rpcrt4 -l advapi32 -l ws2_32 -l mswsock -l shlwapi /c/dev/amsterdamcoin_v3.0/src/leveldb/libleveldb.a /c/dev/amsterdamcoin_v3.0/src/leveldb/libmemenv.a
obj/init.o: In function `Z5Hash9IPcE7uint256T_S2_':
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:67: undefined reference to `sph_blake512_init'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:69: undefined reference to `sph_blake512'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:70: undefined reference to `sph_blake512_close'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:72: undefined reference to `sph_bmw512_init'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:74: undefined reference to `sph_bmw512'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:75: undefined reference to `sph_bmw512_close'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:79: undefined reference to `sph_groestl512_init'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:81: undefined reference to `sph_groestl512'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:82: undefined reference to `sph_groestl512_close'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:92: undefined reference to `sph_groestl512_init'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:94: undefined reference to `sph_groestl512'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:95: undefined reference to `sph_groestl512_close'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:97: undefined reference to `sph_jh512_init'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:99: undefined reference to `sph_jh512'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:100: undefined reference to `sph_jh512_close'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:104: undefined reference to `sph_blake512_init'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:106: undefined reference to `sph_blake512'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:107: undefined reference to `sph_blake512_close'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:117: undefined reference to `sph_keccak512_init'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:119: undefined reference to `sph_keccak512'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:120: undefined reference to `sph_keccak512_close'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:122: undefined reference to `sph_skein512_init'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:124: undefined reference to `sph_skein512'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:125: undefined reference to `sph_skein512_close'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:129: undefined reference to `sph_keccak512_init'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:131: undefined reference to `sph_keccak512'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:132: undefined reference to `sph_keccak512_close'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:136: undefined reference to `sph_jh512_init'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:138: undefined reference to `sph_jh512'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:139: undefined reference to `sph_jh512_close'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:111: undefined reference to `sph_bmw512_init'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:113: undefined reference to `sph_bmw512'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:114: undefined reference to `sph_bmw512_close'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:86: undefined reference to `sph_skein512_init'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:88: undefined reference to `sph_skein512'
c:\dev\amsterdamcoin_v3.0\src/hashblock.h:89: undefined reference to `sph_skein512_close'
obj/net.o: In function `Z13ThreadMapPortv':
c:\dev\amsterdamcoin_v3.0\src/net.cpp:1122: undefined reference to `_imp__upnpDiscover'
c:\dev\amsterdamcoin_v3.0\src/net.cpp:1133: undefined reference to `_imp__UPNP_GetValidIGD'
c:\dev\amsterdamcoin_v3.0\src/net.cpp:1188: undefined reference to `_imp__freeUPNPDevlist'
c:\dev\amsterdamcoin_v3.0\src/net.cpp:1190: undefined reference to `_imp__FreeUPNPUrls'
c:\dev\amsterdamcoin_v3.0\src/net.cpp:1138: undefined reference to `_imp__UPNP_GetExternalIPAddress'
c:\dev\amsterdamcoin_v3.0\src/net.cpp:1170: undefined reference to `_imp__strupnperror'
c:\dev\amsterdamcoin_v3.0\src/net.cpp:1166: undefined reference to `_imp__UPNP_AddPortMapping'
c:\dev\amsterdamcoin_v3.0\src/net.cpp:1180: undefined reference to `_imp__UPNP_DeletePortMapping'
c:\dev\amsterdamcoin_v3.0\src/net.cpp:1182: undefined reference to `_imp__freeUPNPDevlist'
c:\dev\amsterdamcoin_v3.0\src/net.cpp:1183: undefined reference to `_imp__FreeUPNPUrls'
collect2.exe: error: ld returned 1 exit status
make: *** [amsterdamcoind.exe] Error 1`

windows 10 with

> $ g++ -v
Using built-in specs.
COLLECT_GCC=c:\mingw32\bin\g++.exe
COLLECT_LTO_WRAPPER=c:/mingw32/bin/../libexec/gcc/i686-w64-mingw32/4.9.2/lto-wrapper.exe
Target: i686-w64-mingw32
Configured with: ../../../src/gcc-4.9.2/configure --host=i686-w64-mingw32 --build=i686-w64-mingw32 --target=i686-w64-mingw32 --prefix=/mingw32 --with-sysroot=/c/mingw492/i686-492-posix-dwarf-rt_v3-rev1/mingw32 --with-gxx-include-dir=/mingw32/i686-w64-mingw32/include/c++ --enable-shared --enable-static --disable-multilib --enable-languages=ada,c,c++,fortran,objc,obj-c++,lto --enable-libstdcxx-time=yes --enable-threads=posix --enable-libgomp --enable-libatomic --enable-lto --enable-graphite --enable-checking=release --enable-fully-dynamic-string --enable-version-specific-runtime-libs --disable-sjlj-exceptions --with-dwarf2 --disable-isl-version-check --disable-cloog-version-check --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-bootstrap --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-gnu-as --with-gnu-ld --with-arch=i686 --with-tune=generic --with-libiconv --with-system-zlib --with-gmp=/c/mingw492/prerequisites/i686-w64-mingw32-static --with-mpfr=/c/mingw492/prerequisites/i686-w64-mingw32-static --with-mpc=/c/mingw492/prerequisites/i686-w64-mingw32-static --with-isl=/c/mingw492/prerequisites/i686-w64-mingw32-static --with-cloog=/c/mingw492/prerequisites/i686-w64-mingw32-static --enable-cloog-backend=isl --with-pkgversion='i686-posix-dwarf-rev1, Built by MinGW-W64 project' --with-bugurl=http://sourceforge.net/projects/mingw-w64 CFLAGS='-O2 -pipe -I/c/mingw492/i686-492-posix-dwarf-rt_v3-rev1/mingw32/opt/include -I/c/mingw492/prerequisites/i686-zlib-static/include -I/c/mingw492/prerequisites/i686-w64-mingw32-static/include' CXXFLAGS='-O2 -pipe -I/c/mingw492/i686-492-posix-dwarf-rt_v3-rev1/mingw32/opt/include -I/c/mingw492/prerequisites/i686-zlib-static/include -I/c/mingw492/prerequisites/i686-w64-mingw32-static/include' CPPFLAGS= LDFLAGS='-pipe -L/c/mingw492/i686-492-posix-dwarf-rt_v3-rev1/mingw32/opt/lib -L/c/mingw492/prerequisites/i686-zlib-static/lib -L/c/mingw492/prerequisites/i686-w64-mingw32-static/lib -Wl,--large-address-aware'
Thread model: posix
gcc version 4.9.2 (i686-posix-dwarf-rev1, Built by MinGW-W64 project)

**Comment by keesdewit82** [comment]
Solved in commit: https://github.com/CoinProjects/AmsterdamCoin/commit/c2ee252b079f1b41280d87987321a8cd3fa92cfb

Please fetch this commit and clean/build again
